### ISSUE TITLE
Great Switcher -  Fan Control Possible?

### ISSUE THREAD

**Issue by dmckillican** [nitaybz/homebridge-http-multiswitch#1]
Hi,

This is a great switcher and I have it working neatly. Just a question though (perhaps a feature request), is it possible to show a device as a multi-speed Fan?

For example, I have a broad link RM Pro with the android plugin allowing control by HTTP. I have set up the multi switch and it works perfectly, but obviously shows as 4 individual switches (Off, Low, Medium and High).

Is it possible to have this show as a single device with multiple options, similar to AC and HomeKit fan controllers?

Thanks, Drew

**Comment by nitaybz** [comment]
Hey @dmckillican , unfortunately that's not how the plugin works, that is a totally different way of working, what you are looking for is an http-fan plugin to support the power level of the fan.
I don't have any controlled fan and that is why I did not create such and don't have a way to test any of those. maybe you can ask someone with this kind of controlled fan to try and make one of those.
