### ISSUE TITLE
Additional execution of HTTP

### ISSUE THREAD

**Issue by mczac** [nitaybz/homebridge-http-multiswitch#2]
Hello, great plug-in, thanks a lot!!!

Is it possible to add an execution of additional HTTP line.
In my case I managed to adjust your plug-in to control Bang & Olufsen speaker, however it requires 2 HTTP GET commands, one to set the Data (Music Source) and Second Get to execute the timer. 
Just additional parameter in config with full URL that is executed in case if declared in the config.json right after any multiswitch HTTP command would be fantastic!

Many thanks,
Peter

**Comment by nitaybz** [comment]
Hi @mczac 

I think an easier and quick fix for you is to create another switch and make an automation which will turn on the second switch when the first one turned on.
a harder way of doing it is to make the URL of the switch refer to a page that calls 2 other URLs.

both of the options would be much easier to do than me rewriting the script.

if i'll see this option is indeed necessary for a lot of people I will consider making it.

Hope I did help your issue :)
