### ISSUE TITLE
Switch on/off state

### ISSUE THREAD

**Issue by mczac** [nitaybz/homebridge-http-multiswitch#3]
Hello, what on_body off_body URLs need to return? True/False?

**Comment by nitaybz** [comment]
the plugin does not require anything in the body other than the answer 200(ok) for the call

**Comment by mczac** [comment]
I want the switch to return its on/off state, what results should the on_body and off_body URL provide?
thanks

**Comment by nitaybz** [comment]
there is no status request in this plugin.... sorry
